<?php
return [
	'menu' => [
        'list' => 'menu.list',
		'add' => 'menu.add',
		'edit' => 'menu.edit',
		'delete' => 'menu.delete',
        'show'   => 'menu.show',
	],
	'permission' => [
		'list' => 'permission.list',
		'add' => 'permission.add',
		'edit' => 'permission.edit',
		'delete' => 'permission.delete',
        'show'   => 'permission.show',
	],
    'role' => [
        'list' => 'role.list',
        'add' => 'role.add',
        'edit' => 'role.edit',
        'delete' => 'role.delete',
        'show'   => 'role.show',
    ],
    'user' => [
        'list' => 'user.list',
        'add' => 'user.add',
        'edit' => 'user.edit',
        'delete' => 'user.delete',
        'show'   => 'user.show',
    ],
    'videotag' => [
        'list' => 'videotag.list',
        'add' => 'videotag.add',
        'edit' => 'videotag.edit',
        'delete' => 'videotag.delete',
    ],
    'video' => [
        'list' => 'video.list',
        'add' => 'video.add',
        'edit' => 'video.edit',
        'delete' => 'video.delete',
    ],
    'busesroute' => [
        'list' => 'busesroute.list',
        'add' => 'busesroute.add',
        'edit' => 'busesroute.edit',
        'delete' => 'busesroute.delete',
    ],
    'buses' => [
        'list' => 'buses.list',
        'add' => 'buses.add',
        'edit' => 'buses.edit',
        'delete' => 'buses.delete',
        'show' => 'buses.show',
    ],
    'driver' => [
        'list' => 'driver.list',
        'add' => 'driver.add',
        'edit' => 'driver.edit',
        'delete' => 'driver.delete',
        'show' => 'driver.show',
    ],
    'articles' => [
        'list' => 'articles.list',
        'add' => 'articles.add',
        'edit' => 'articles.edit',
        'delete' => 'articles.delete',
        'show' => 'articles.show',
    ],
    'categorys' => [
        'list' => 'categorys.list',
        'add' => 'categorys.add',
        'edit' => 'categorys.edit',
        'delete' => 'categorys.delete',
        'show' => 'categorys.show',
    ],
    'comments' => [
        'list' => 'comments.list',
        'add' => 'comments.add',
        'edit' => 'comments.edit',
        'delete' => 'comments.delete',
        'show' => 'comments.show',
    ],
    'goodscategorys' => [
        'list' => 'goodscategorys.list',
        'add' => 'goodscategorys.add',
        'edit' => 'goodscategorys.edit',
        'delete' => 'goodscategorys.delete',
        'show' => 'goodscategorys.show',
    ],
    'goods' => [
        'list' => 'goods.list',
        'add' => 'goods.add',
        'edit' => 'goods.edit',
        'delete' => 'goods.delete',
        'show' => 'goods.show',
    ],
    'goodsstock' => [
        'list' => 'goodsstock.list',
        'add' => 'goodsstock.add',
        'edit' => 'goodsstock.edit',
        'delete' => 'goodsstock.delete',
        'show' => 'goodsstock.show',
    ],
    'goodsorder' => [
        'list' => 'goodsorder.list',
        'add' => 'goodsorder.add',
        'edit' => 'goodsorder.edit',
        'delete' => 'goodsorder.delete',
        'show' => 'goodsorder.show',
    ],
    'note' => [
        'list' => 'note.list',
        'add' => 'note.add',
        'edit' => 'note.edit',
        'delete' => 'note.delete',
        'show' => 'note.show',
    ],
    'system' => [
        'list' => 'system.index',
        'login' => 'system.login'
    ]
];
